export const createAffiliateLinkSuccessMessage = 'You successfully created affiliate link!';

export const localeValues = [
    'en-MT',
    'en-KW',
    'en-PK',
    'en-UA',
    'nb-NO',
    'en-SA',
    'ar-MA',
    'en-AL',
    'it-IT',
    'fr-MQ',
    'en-AU',
    'el-GR',
    'fr-FR',
    'sv-SE',
    'es-ES',
    'en-PR',
    'ru-BY',
    'en-ZA',
    'es-PA',
    'ko-KR',
    'en-NZ',
    'es-MX',
    'pt-BR',
    'de-AT',
    'en-NL',
    'tr-CY',
    'fa-IR',
    'en-CA',
    'it-CN',
    'th-TH',
    'en-PH',
    'de-DE',
    'en-IN',
    'en-GB',
    'en-NG',
    'tr-TR',
    'az-AZ',
    'ru-GE',
    'vi-VN',
    'en-US',
    'ru-RU'
];
export const localeDefaultValue = localeValues[0];
